.eslintignore
.eslintrc.json
app/js/app.js
app/js/entry.js
package-lock.json
package.json
webpack.config.js

Added linting as a prehook. @adibas03 @coderwithattitude please review, merge and delete branch when done.

Added linting as a pre-hook commit

---

.travis.yml

Set up Travis to deploy the _develop_ branch to the folder in the AWS bucket.

Travis initial setup

---

package-lock.json
package.json
webpack/base.config.js

Added mobx and related babel plugins.

Added Mobx

---

app/entry.js
package-lock.json
package.json

Added the correct select2 version

---

app/components/ScheduleWizard/TimeSettings/TimeComponent.js
app/scss/style.scss

Minor UI style changes. @adibas03 @Kuzirashi please merge so that we have a prettier demo on the webinar today.

Time settings

---

app/components/Common/ScheduleWizard.js

Quick css updates

---

app/components/Header/Header.js
app/components/Search/SearchOverlay.js
app/components/Search/SearchResult.js
app/scss/style.scss
app/stores/TransactionStore.js

Fixed issues with the search and the search overlay navigation to transactions.

General fixes for the search overlay

---

app/components/Common/ScheduleWizard.js
app/components/ScheduleWizard/ScheduleRoute.js
app/scss/style.scss

Matched nav tabs for the schedule wizard with the design.

Updated the schedule wizard nav to match design

---

app/components/Common/URLNotFound.js
app/scss/style.scss

Adjusted the design according to http://pages.revox.io/dashboard/3.0.0/html/simply_white/404.html. Omitted the search bar for now because not sure if necessary.

Matched the style of the 404 page

---

app/components/Common/URLNotFound.js
app/components/Search/SearchOverlay.js
app/components/TransactionScanner/TransactionNotFound.js
app/components/TransactionsRoute/TransactionDetailsRoute.js
app/scss/style.scss
app/stores/TransactionStore.js

Added a check if the tx exists before displaying tx details.

404 Missing Transaction

---

app/components/TimeNode/TimeNodeProve.js
app/components/TimeNode/TimeNodeRoute.js
app/components/TimeNode/TimeNodeStatistics.js
app/components/TimeNode/TimeNodeWallet.js
app/stores/TimeNodeStore.js
package.json

Finished all the functionality to import a wallet and confirm DAY token ownership.

[FEATURE] TimeNode - DAY Token check + Balances info

---

app/components/TimeNode/TimeNodeStatistics.js
app/stores/TimeNodeStore.js
package-lock.json

[Feature][TimeNode] Low DAY balance notification

---

app/components/TransactionScanner/TransactionDetails.js
package-lock.json
package.json

moved getFrozenStatus() call to componentDidMount()

fixed state setting warning

---

app/components/Common/Alert.js
app/components/TimeNode/TimeNodeStatistics.js
app/components/TimeNode/TimeNodeWallet.js
app/stores/TimeNodeStore.js
package-lock.json
package.json

Added password validations for importing a wallet + UI improvements.

[Validation] Timenode wallet

---

app/components/ScheduleWizard/ConfirmSettings.js
webpack/base.config.js

added sourcemap to webpack for easier debugging.

added sourcemap to webpack base config

---

app/components/Search/SearchOverlay.js
app/stores/TransactionStore.js
app/stores/TransactionsCache.js

Removed `@computed` properties from getter functions that don't compute anything.

[FIX] Incorrect use @computed + Search UI fixes

---

app/components/App/App.js
app/components/Common/ScheduleWizard.js
app/index.html
app/scss/style.scss

This PR is made to fix the usability issues of the DApp on mobile (scrolling etc.).
More responsiveness PRs coming up.

[FEATURE] Mobile responsiveness v1

---

app/components/Common/ScheduleWizard.js
app/components/ScheduleWizard/BountySettings.js
app/components/ScheduleWizard/ConfirmSettings.js
app/components/ScheduleWizard/InfoSettings.js
app/components/ScheduleWizard/TimeSettings.js
app/components/ScheduleWizard/TimeSettings/TimeComponent.js
app/components/SidePanel/SidePanel.js
app/components/TimeNode/TimeNodeLogs.js
app/components/TimeNode/TimeNodeMain.js
app/components/TimeNode/TimeNodeRoute.js
app/components/TimeNode/TimeNodeStatistics.js
app/components/TransactionScanner/TransactionDetails.js
app/components/TransactionScanner/TransactionScanner.js
app/components/TransactionScanner/TransactionsTable.js
app/components/TransactionsRoute/TransactionDetailsRoute.js
app/components/TransactionsRoute/TransactionsCompleted.js
app/components/TransactionsRoute/TransactionsScheduled.js
app/scss/style.scss

A ton of UI and mobile responsiveness fixes/features.

[FEATURE] Mobile responsiveness v2

---

app/components/TimeNode/TimeNodeStatistics.js
app/js/eac-worker.js
app/stores/TimeNodeStore.js
package-lock.json
package.json

Depends on this: https://github.com/ethereum-alarm-clock/eac.js-client/pull/7

[FEATURE] TimeNode graph shows executed transactions sorted hourly

---

app/components/ScheduleWizard/ConfirmSettings.js
app/scss/style.scss

@adibas03 Here's an update to the issue you raised.
I also increased the height of the element to accommodate the error without creating a scrollbar.

[FIX] Moved error to both columns

---

app/components/App/App.js
app/components/SidePanel/SidePanel.js

Added a location listener to App.js

[FIX] SidePanel Highlights

---

app/components/Common/MetamaskComponent.js

Tracks the changes in MetaMask (on component state change) and avoids duplicate notifications.

[FIX] MetaMask notification state tracking

---

app/components/ScheduleWizard/ScheduleWizard.js
app/scss/style.scss

Added:
- Visual feedback when user presses the Schedule button
- Error management in case the user cancels the MetaMask popup

Fade screen on pressing schedule + error management

---

app/components/TransactionScanner/TransactionDetails.js
app/components/TransactionsRoute/TransactionDetailsRoute.js
app/components/TransactionsRoute/TransactionsCompleted.js
app/components/TransactionsRoute/TransactionsRoute.js
app/components/TransactionsRoute/TransactionsScheduled.js

- The Tx details window looks much better
- Transaction status updates after cancelling
- Hiding the cancel button when the transaction has already been cancelled

[FIX] Look of the Tx details window + cancel button functionality

---

app/components/ScheduleWizard/ScheduleWizard.js

@kosecki123 this is the fix to the weird behaviour when the Scheduling.. button wouldn't revert to normal text.

[FIX] Scheduling button handling in case of an error

---

app/js/eac-worker.js
app/stores/TimeNodeStore.js

[FIX] On insuficient DAY balance stop

---

app/stores/TimeNodeStore.js

Enables the user to run a TimeNode in case he is a TimeMint owner.

[FEATURE] TimeMint check

---

app/components/TimeNode/TimeNodeProve.js

Implements #204 
Currently the changes are not persistent, but the user is able to go back and submit a new wallet file at least.

Add ability to reset timenode prove process

---

app/components/TimeNode/TimeNodeMain.js
app/components/TimeNode/TimeNodeProve.js
app/components/TimeNode/TimeNodeSettings.js
app/js/eac-worker-message-types.js
app/js/eac-worker.js
app/scss/style.scss
app/stores/TimeNodeStore.js

Adds two options to the TimeNode settings:
- *Reset stats* - Resets the executed transaction counter and claimed ETH counter to 0
- *Detach Wallet* - Enables the user to detach a wallet from a TimeNode and re-attach a different one.

[FEATURE] Detach TimeNode

---

app/components/TimeNode/TimeNodeStatistics.js
app/js/eac-worker.js
package-lock.json
package.json

Depends on https://github.com/ethereum-alarm-clock/eac.js-client/pull/19

[FIX] Stats

---

app/js/eac-worker.js
app/stores/TimeNodeStore.js
package.json

dependent on:
https://github.com/ethereum-alarm-clock/eac.js-client/pull/24

[FEATURE] Implement eac.js-client walletStores update

---

docker-compose.yml
docker/ganache/Dockerfile
docker/ganache/startup.sh

Changes:
- Decreases contracts deployment time in Docker containers from ~6 min to 15 seconds

[Docker] Faster contracts deployment

---

__tests__/__snapshots__/Header.unit.test.js.snap
app/components/Header/Header.js

Changes:
- Added network name to the top bar
- Fixed contracts icon not hiding from the top bar when in responsive (mobile) mode
- Ran prettifier

Add network name to top bar + contracts icon responsiveness

---

__tests__/__snapshots__/Header.unit.test.js.snap
app/components/Common/Faucet.js
app/components/Common/MetamaskComponent.js
app/components/Header/Header.js
app/components/TimeNode/TimeNodeRoute.js
app/components/TimeNode/TimeNodeUnlock.js
app/components/TimeNode/TimeNodeWallet.js
app/components/TimeNode/index.js
app/stores/TimeNodeStore.js
package-lock.json

Asks the user for the wallet password every time he opens the TimeNode screen to enable the TimeNode.
Please squash commits if merging.

[FEATURE] TimeNode Wallet Improvements

---

__mocks__/eacWorkerMock.js
__tests__/stores/TimeNodeStore.unit.test.js
app/stores/TimeNodeStore.js
package.json

Many changes here are prettier formatting. I've written test case to avoid calling decrypt on password.

[FIX] Fix TimeNode wallet handling.

---

app/components/TransactionScanner/TransactionsTable.js
app/scss/style.scss
package-lock.json
package.json

Quick fix - show pointers 
on pagination in transactions list.
+ added missing dependency `websocket`.

Add pointer to pagination

---

app/components/ScheduleWizard/BountySettings.js
app/components/ScheduleWizard/BountySettings/BountyEstimator.js
app/components/ScheduleWizard/BountySettings/index.js
app/stores/ScheduleStore.js
app/stores/TransactionFetcher.js
app/stores/TransactionStore.js
package-lock.json

Bounty estimator widget

---

app/stores/KeenStore.js
app/stores/index.js

Dependent on  
https://github.com/ethereum-alarm-clock/eac.js-lib/pull/15  
https://github.com/ethereum-alarm-clock/eac.js-client/pull/39
https://github.com/ethereum-alarm-clock/eac.js-cli/pull/26

[FEATURE] Analytics client contracts

---

app/components/TimeNode/TimeNodeProve.js

Merging the https://github.com/chronologic/eth-alarm-clock-dapp/pull/293 hotfix into the develop branch as well.

[HOTFIX] Align signing instructions to recent MyCrypto changes

---

docker/eac_protocol/Dockerfile

Fixes an issue with addresses on Docker not matching.

Update Docker script with latest EAC

---

app/components/TimeNode/ExecutedGraph.js
app/components/TimeNode/TimeNodeStatistics.js
app/js/eac-worker.js
app/stores/TimeNodeStore.js
app/stores/TransactionStore.js

Depends on https://github.com/ethereum-alarm-clock/eac.js-client/pull/47.
Fixes:
- Issues with calculating the cost of TimeNodes
- TimeNode executed transactions graph now shows only the transactions from the last 24 hours
- Random error that would sometimes error when scheduling a transaction on a local blockchain

[FIX] TimeNode issues

---

__tests__/stores/TimeNodeStore.unit.test.js
app/components/TimeNode/TimeNodeStatistics.js
app/stores/TimeNodeStore.js
package-lock.json

Fixes TimeNode storage issues when the TimeNode is built into an Electron app.

[FIX] Electron: Transition cookie storage to localStorage

---

app/components/TimeNode/TimeNodeProve.js
package-lock.json

Makes the DAY token signing instructions clearer for our users.

Better DAY token proving instructions

---

package.json

Reverts chronologic/eth-alarm-clock-dapp#350

Revert "fix(package): update bignumber.js to version 7.2.1"

---

package.json

fix(package): update mobx to version 5.0.2

---

package.json

chore(package): update autoprefixer to version 8.6.2

---

package.json

chore(package): update react-hot-loader to version 4.3.3

---

app/components/Common/Select.js
app/components/ScheduleWizard/InfoSettings.js
app/config/web3Config.js
app/services/web3.js
jsconfig.json
package-lock.json

**Schedule DAI token transfer using Chronos DApp** (video)
[![Schedule DAI token transfer using Chronos DApp](https://img.youtube.com/vi/VepBeGyFCUA/0.jpg)](https://youtu.be/VepBeGyFCUA)

[FEATURE] Make the DAI token transfers native

---

package.json

chore(package): update lint-staged to version 7.2.2

---

package.json

fix(package): update eac.js-lib to version 2.3.3

---

package-lock.json
package.json

Updated:
- `timenode-core` - v4.3.0
- `eac.js-lib` - v2.3.6

timenode-core 4.3.0

---

app/components/TimeNode/TimeNodeSettings.js
app/stores/TimeNodeStore.js
package-lock.json
package.json

push update to https://app.chronologic.network

[UPDATE] update to 0.9.14

---

app/js/eac-worker.js

Necessary for a smooth transition of the users from the old stats to the new ones.

[Compatibility] StatsDB name

---

app/components/TimeNode/TimeNodeUnlock.js

[FEATURE] Detach the wallet on password screen

---

app/components/TimeNode/Modals/ConfirmEconomicStrategyModal.js
app/components/TimeNode/TimeNodeSettings.js
app/stores/TimeNodeStore.js

- Adds a `maxGasSubsidy` economic strategy option to the DApp

[FEATURE] maxGasSubsidy

---

app/js/eac-worker.js

This depends on https://github.com/ethereum-alarm-clock/timenode-core/pull/236 to be merged and released.

Adjust to StatsDB having init method for loading

---

app/components/TimeNode/Modals/ConfirmEconomicStrategyModal.js
app/components/TimeNode/TimeNodeSettings.js
app/components/TimeNode/TimeNodeStatistics.js
package-lock.json

Adds a notification to the TimeNode screen whenever `claiming` is turned OFF.
Additional:
- Fixes a new-found claiming ON/OFF bug where the TimeNode wouldn't restart after the switch was toggled and changes saved.

[FEATURE] Claiming OFF Notification

---

app/components/TimeNode/Modals/ConfirmEconomicStrategyModal.js
app/components/TimeNode/TimeNodeSettings.js

Shows a warning whenever a user has changed some of the settings but hasn't pressed the `Save` button.

[TimeNode Settings] Unsaved Changes warning

---

app/components/Common/ConfirmModal.js
app/components/TimeNode/TimeNodeMain.js
app/components/TimeNode/TimeNodeSettings.js
package-lock.json

- Adds a popup when switching away from unsaved settings
TO-DO:

[FEATURE] Unsaved changes pop-up

---

package.json

chore(package): update eac.js-lib to version 2.4.2

---

__tests__/__snapshots__/Header.unit.test.js.snap
app/components/Header/Header.js
package-lock.json

Fixes the TimeNode counter loading indefinitely on any network with 0 TimeNodes

[FIX] TimeNode counter other network support

---

__tests__/Header.unit.test.js
__tests__/stores/TimeNodeStore.unit.test.js
app/components/Header/NetworkChooser.js
app/components/Modals/CustomProviderModal.js
app/stores/TimeNodeStore.js
package-lock.json

Fixes issue: https://github.com/chronologic/eth-alarm-clock-dapp/issues/612

[FIX] DAY token balance inconsistencies

---

app/components/Header/Header.js
app/components/Header/NetworkChooser.js
app/components/TimeNode/Modals/ConfirmEconomicStrategyModal.js
app/components/TimeNode/Modals/TimeNodeDetachModal.js
app/components/TimeNode/Modals/TimeNodeResetStatsModal.js
app/components/TimeNode/TimeNodeMain.js
app/components/TimeNode/TimeNodeProve.js
app/components/TimeNode/TimeNodeRoute.js
app/components/TimeNode/TimeNodeSettings.js
app/components/TimeNode/TimeNodeStatistics.js
app/components/TimeNode/TimeNodeUnlock.js
app/js/eac-worker.js
app/services/web3.js
app/stores/KeenStore.js
app/stores/TimeNodeStore.js
package-lock.json

Fixes issue https://github.com/chronologic/eth-alarm-clock-dapp/issues/618.
Also:
- Fix checking DAY balance when signing on Ropsten/Kovan
- Moved all intervals from components to TimeNodeStore
- Changed TimeNode netId fetching logic
- Improved logic for managing a locked wallet
- Shows info bubble for TimeNode counter when on `/timenode` screen and the TimeNode is locked

[FIX] DAY balance check

---

__tests__/TransactionScanner.unit.test.js
__tests__/stores/TransactionStore.unit.test.js
app/components/TransactionScanner/TransactionDetails.js
app/components/TransactionScanner/TransactionRow.js
app/services/index.js
app/services/network-aware-storage.js
app/services/network-specific-key-modifier.js
app/services/storage.js
app/services/transaction-helper.js
app/stores/TransactionCache.js
app/stores/TransactionFetcher.js
app/stores/TransactionStore.js
app/stores/index.js
package-lock.json

- [BUGFIX] Fix problem where cache wasn't taken into consideration because network wasn't set yet (trying to get null-TransactionCache-xyz instead of 42-TransactionCache-xyz)
- [BUGFIX] Introduce chunking of requests, so transactions on Ropsten will be loaded (after more than 210s for 7000 addresses, but they will load)
- [CODE QUALITY] Move transaction helper methods to transaction-helper file
- [PERFORMANCE] Avoid calling `moment().unix()` for each object in loop, instead get it before loop and pass to methods called in loop

[BUGFIX] Fix transactions not loading on Ropsten.

---

app/services/index.js
app/services/network-aware-storage.js

[FEATURE] Store cache in IndexedDB instead of Local Storage.

---

electron-app/main/index.js
package-lock.json

Following https://electronjs.org/docs/api/menu on how to add the About tab.
Fixes issue https://github.com/chronologic/eth-alarm-clock-dapp/issues/617.
Tested on:

Electron: About

---

__tests__/App.unit.test.js
__tests__/TransactionDetails.unit.test.js
app/components/Common/ValueDisplay.js
app/components/ScheduleWizard/InfoSettings.js
app/components/TransactionScanner/TransactionDetails.js
app/services/index.js
app/services/token-helper.js
app/services/web3.js
package-lock.json
package.json

Depends on https://github.com/ethereum-alarm-clock/timenode-core/pull/255.

[FEATURE] Apply DRY principle to getting web3 provider.

---

app/components/TimeNode/TimeNodeStatistics.js
app/js/eac-worker-message-types.js
app/js/eac-worker.js
app/stores/TimeNodeStore.js

More reliable and faster starting and balance checking.
* Improve the initial balance check
* Rely on worker feedback after timenode start
* Remove excessive stats updates

TimeNode improvements

---

app/stores/TimeNodeStore.js
package-lock.json

Fixes an error on the Mainnet where a user was not able to create the TimeNode by using a TimeMint.

[FIX] TimeMint Check

---

app/components/TransactionScanner/TransactionDetails.js
app/services/transaction-helper.js

* Fix cancel state detection 
* Improve loading speed

Transaction details improvements 

---

app/components/Common/URLNotFound.js

Closes https://github.com/chronologic/eth-alarm-clock-dapp/issues/698.

[FIX] 404 Report Link

---

__tests__/__snapshots__/TransactionDetails.unit.test.js.snap
app/components/TransactionScanner/TransactionDetails.js
app/scss/style.scss
package-lock.json

[FEATURE] Improve Cancel button clarity

---

app/components/ScheduleWizard/ConfirmSettings.js

[FIX] Better scheduling input error messages

---

app/components/TimeNode/TimeNodeProve.js
package-lock.json

Fixes:
> react-dom.development.js:492 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
>     in TimeNodeProve (created by inject-TimeNodeProve-with-timeNodeStore)
>     in inject-TimeNodeProve-with-timeNodeStore (created by TimeNodeRoute)

[BUGFIX] Fix setState on unmounted component.

---

app/components/TimeNode/StatisticsComponents/ExecutedGraph.js
app/components/TimeNode/TimeNodeDashboard.js
package-lock.json

- Better graph update procedure
- Fixes updates button not triggering properly

Executed Graph Improvements

---

__tests__/SidePanel.unit.test.js
__tests__/__snapshots__/SidePanel.unit.test.js.snap
app/components/App/App.js
app/components/Header/Header.js
app/components/Header/NetworkChooser.js
app/components/Header/NetworkChooserModal.js
app/components/SidePanel/SidePanel.js
app/scss/style.scss
app/stores/TimeNodeStore.js

Bonus:
- Improve CSS of SidePanel (fix alignment of current block)

[BUGFIX] Show Network chooser in sidebar.

---

app/components/TimeNode/Network/ActiveTimeNodesGraph.js
app/components/TimeNode/Network/TimeBountiesGraph.js
app/components/TimeNode/TimeNodeNetwork.js
app/js/eac-worker.js
app/stores/KeenStore.js
app/stores/TimeNodeStore.js

**Changelog**
- The Active TimeNode chart now display historical data as soon as it's opened - doesn't need to gather data
- Improved graphs refreshing mechanism and other fixes

[FIX] Various TimeNode Chart fixes

---

app/stores/TransactionFetcher.js

Make metrics display on Electron.

[BUGFIX] Fix metrics display on Electron.

---

app/components/TimeNode/TimeNodeNetwork.js
app/stores/KeenStore.js

- Transfers Keen.io requests fetching interval from store to component.
- Prevents the overflow of Keen.io requests when the user is not on the TimeNode page

[FIX] Keen requests

---

app/components/TimeNode/TimeNodeNetwork.js
app/stores/KeenStore.js
package-lock.json

- Fixes issue where blacklisting is not detected
- Show warning on active timenodes graph when blaclisted

[FIX] Blacklisted warning

---

__mocks__/eacWorkerMock.js
app/components/TimeNode/TimeNodeNetwork.js
app/stores/TimeNodeStore.js
electron-app/main/index.js
package-lock.json
package.json
webpack/base.config.js
webpack/electron.dev.config.js
webpack/electron.prod.config.js

This is more future-proof worker bundling solution by GoogleChromeLabs. It leads to removing `interceptFileProtocol` workaround in Electron.

[FEATURE] Use better worker bundling solution by GoogleChromeLabs.

---

__tests__/__snapshots__/SidePanel.unit.test.js.snap
app/stores/TransactionStore.js
package-lock.json
package.json

Description in the title. Depends on new version of eac.js-lib.

Adds fetching for  a better gasPrice estimate from eth gas station

---

app/services/index.js

Now, first time user visits site he will see popup to trust the site or not.
Can be tested by enabling 'Privacy Mode' in MetaMask and visiting site.

Call provider enable before using accounts.

---

__tests__/TimeNodeRoute.unit.test.js
__tests__/__snapshots__/TimeNodeRoute.unit.test.js.snap
app/components/TimeNode/TimeNodeWallet.js

Since there's a rule to exclude #timenodeRoute from GTM tools, this test is to make sure we don't accidentally remove the identifier.

Add test for external tool

---

__tests__/__snapshots__/TransactionDetails.unit.test.js.snap
app/components/Common/Alert.js
app/components/ScheduleWizard/ConfirmSettings.js
app/components/ScheduleWizard/InfoSettings.js
app/components/TransactionScanner/TransactionDetails.js
package-lock.json

Improves the experience/feedback for approving token transfers.
**Video:** https://youtu.be/-gFTF-HKxKQ
**Screenshots**
Step 1. Approval
Step 2. Waiting
Step 3. Approved

[FEATURE] Scheduled token transfer approval information

---

__tests__/__snapshots__/TransactionDetails.unit.test.js.snap
app/components/TransactionScanner/TransactionDetails/ProxySection.jsx

Tutorial itself: https://blog.chronologic.network/ethereum-alarm-clock-proxy-call-explanation-477170847094

[FEATURE] Better explanation of Proxy call

---

__tests__/__snapshots__/SidePanel.unit.test.js.snap
app/components/SidePanel/SidePanel.js
app/config/web3Config.js
app/index.html

This also orders token alphabetically

[FEATURE] Add Automate links

---

app/config/web3Config.js

[FEATURE] Add Dragonereum EGG transfers

---

app/components/Header/Header.js
app/scss/style.scss

[FIX] Responsive Search Icon

---

app/components/Modals/CustomProviderModal.js

[FIX] Custom Provider check fix + simplification
