- app/components/App/App.js
Now we can close the search bar by pressing the Esc button instead of just the X buttom.
> Search overlay Esc key listener

- app/services/notification.js
Added an option to the notifications service to enable persistent notifications.
Previous behaviour:
- All notifications could be closed by clicking the X button on them
New behaviour:
- We have an option to hide the X button so that the users cannot dismiss the popup.
@adibas03 I think this will be useful for your PR: https://github.com/chronologic/eth-alarm-clock-dapp/pull/104
> [FEATURE] Enabled Persistent Notifications

- app/components/TimeNode/TimeNodeStatistics.js
Minor fix - TimeNode graph text "No data yet." overlaying itself.
> [FIX] TimeNode text

- package-lock.json
- package.json
Forcing the new eac.js-lib version that contains optimisations to reduce the size of our final `app.bundle.js`.
Should increase app performance.
> [FIX] Force new eac.js-lib version

- app/js/eac-worker.js
- package.json
set correct timenode endpoint by updating `app>config>web3Config.js` :
https://github.com/chronologic/eth-alarm-clock-dapp/blob/master/app/config/web3Config.js
> [FEATURE] Implement support for websocket endpoints

- app/components/ScheduleWizard/BountySettings/BountyEstimator.js
Fixes a visual bug in the bounty estimator when there is only one bounty in the bucket pool.
> [FIX] Bounty estimator

- app/services/web3.js
MobX v5.x makes use of Proxies, and this breaks some functionality in our DApp.
After the upgrade, the `network` object was wrapped in a Proxy function which blocked it from being sent to the WebWorker.
Removing the @observable flag reverted the `network` property back to a POJO and allowed it to be sent to the WebWorker.
The network is not a dynamic object anyway, since it reloads after every change in the DApp, so having the @observable property has no effect, hence it is safe to be removed.
More on the MobX updates: https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md
> Changes necessary for the new MobX

- app/components/TimeNode/TimeNodeMain.js
- app/components/TimeNode/TimeNodeRoute.js
- app/components/TimeNode/TimeNodeSettings.js
- app/components/TimeNode/TimeNodeStatistics.js
- app/js/eac-worker.js
- app/lib/timenode-util.js
- app/stores/TimeNodeStore.js
- package-lock.json
Solves an issue when the TimeNode would be set to a different provider, it would still fetch balances from the MetaMask provider.
Additional:
- Minor refactors
- Pretty loadbars
- Fixes an issue with showing the incorrect balance upon changing TimeNode wallets
- Fixes a security issue where after changing wallets the TimeNode would not re-ask the wallet password
> Transfer balance fetching from MetaMask to TimeNode web3 provider

- __mocks__/LocalStorageMock.js
- __tests__/stores/TimeNodeStore.unit.test.js
- app/services/storage.js
- app/stores/TimeNodeStore.js
- app/stores/index.js
- package-lock.json
- package.json
- Force TimeNode store to use the storage service
- Add `remove` method to storage service
- Added devDep `acorn5-object-spread` which is needed to build the electron DApp on MacOS
> [Refactor] TimeNode storage service

- app/lib/worker-logger.js
After updating timenode-core to 4.2.9 the logger has to accept address as separate argument
> Adjust logger to accept the address of tx

- app/components/TimeNode/StatisticsComponents/ActionsTable.js
- app/components/TimeNode/TimeNodeStatistics.js
- app/js/eac-worker.js
- app/stores/TimeNodeStore.js
Fixes:
**1. Dashboard**
- `ACTIONS` table column width responsiveness
- `...` pagination entry leading to `href="#"` instead of being inactive
- Lower margins improvement
- Only show `Showing actions: 1-100/500` when there are some actions, otherwise hide
**2. Stats**
- Fixed `CLEAR_STATS` event not being fired after stats have been cleared
> [FIX][TimeNode] Miscellaneous Fixes

- __tests__/ValueDisplay.unit.test.js
- app/components/Common/ValueDisplay.js
- app/components/Common/index.js
- app/components/ScheduleWizard/ScheduleRoute.js
- app/components/ScheduleWizard/ScheduleWizard.js
- app/components/TransactionScanner/BlockOrTimeDisplay.js
- app/components/TransactionScanner/TransactionDetails.js
- app/components/TransactionScanner/TransactionRow.js
- app/components/TransactionsRoute/TransactionsCompleted.js
- app/components/TransactionsRoute/TransactionsOwner.js
- app/components/TransactionsRoute/TransactionsScheduled.js
- package-lock.json
Tests now fail in cases where the `export` command is inserted between a class name and a decorator:
```/home/travis/build/chronologic/[secure]/app/components/Common/ValueDisplay.js
12:1  error  Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.
10 | 
11 | @inject('web3Service')
> 12 | export class ValueDisplay extends Component {
| ^
13 |   render() {
14 |     const { priceInWei } = this.props;
15 |```
Excerpt from a travis build fail: https://travis-ci.org/chronologic/eth-alarm-clock-dapp/builds/425233694?utm_source=github_status&utm_medium=notification
> [FIX] Exports

- app/stores/TransactionStore.js
If gas is `undefined` MetaMask replaces it with its estimation, which instead of `1500000` is `794158`.
> [FEATURE] Estimate gas instead of hard-coding.

- app/js/eac-worker.js
Depends on latest release of `timenode-core`, makes DApp compatible with the change in the config parameters.
> Changes providerUrl -> providerUrls

- electron-app/main/index.js
- package-lock.json
With the current default window width, the status bar is not visible when running in Electron. Increasing the width stops the responsive view from triggering. Should be fixed in a better way, but works for now.
> [ELECTRON] Larger initial window width

- app/components/TimeNode/Network/ProcessedTransactionsGraph.js
- app/components/TimeNode/Network/index.js
- app/components/TimeNode/TimeNodeNetwork.js
- app/js/eac-worker-message-types.js
- app/js/eac-worker.js
- app/stores/TimeNodeStore.js
**Changelog**
- TimeNodes can now see a new graph that shows the number of transactions that have been processed (executed) each hour for the past 24 hours.
- Changed all graphs to be **bar charts** because the other charts don't match the use
**Screenshot from Ropsten**
> [FEATURE] Processed Transactions Graph

- electron-app/main/index.js
- package-lock.json
Closes https://github.com/chronologic/eth-alarm-clock-dapp/issues/820.
Replaces the electron `logs` folder with `userData` because `logs` doesn't work on Linux.
Tested on:
> [FIX] [ELECTRON] Logs folder

- __mocks__/EacServiceMock.js
- __tests__/App.unit.test.js
- __tests__/Header.unit.test.js
- __tests__/SidePanel.unit.test.js
- __tests__/__snapshots__/SidePanel.unit.test.js.snap
- app/components/Header/Header.js
- app/components/SidePanel/SidePanel.js
- app/scss/style.scss
- app/stores/EacStore.js
- app/stores/index.js
- package-lock.json
**New** 
- `EacStore` - Stores information about the total ETH transferred count + info about contracts
- Replaced `&nbsp;` on starts and ends of divs with `margin` CSS styling
- Add missing loader to Block Number analytics
> [FEATURE] [ANALYTICS] Total ETH transferred counter

- app/services/web3.js
`window.web3.currentProvider` will soon be discontinued. Use `window.ethereum` instead as future-proofing.
> Replace window.web3.currentProvider with window.ethereum

- package-lock.json
- package.json
Because of problems introduced in web3 0.20.7, especially commit:
https://github.com/ethereum/web3.js/commit/b4c1542ddb5284267f6814ba0106bfbbc83fe166
There are problems with CORS.
This fixes #905.
> [BUGFIX] Downgrade web3 to v0.20.6

- .eslintrc.json
- app/components/Common/AwaitingMining.js
- app/components/TransactionScanner/TransactionDetails.js
- app/components/TransactionsRoute/TransactionDetailsRoute.js
- app/services/web3.js
- app/stores/TransactionCache.js
- app/stores/TransactionStore.js
a) Scheduling when staying on the same page: https://youtu.be/aaR345cLIXk
Here we take advantage of local data from scheduling view (we save it in memory, until tab is closed)
b) Scheduling when transaction has been scheduled in different tab (no local data): 
https://youtu.be/a0M2rPkp8c0
> [FEATURE] Show transaction details faster after scheduling
